// Resource IDs for Settings Dialog
#pragma once

// Dialog IDs
#define IDD_SETTINGS_DIALOG 100

// Tab Control
#define IDC_TAB_CONTROL 1000

// Quality Section
#define IDC_LABEL_QUALITY 1100
#define IDC_COMBO_QUALITY 1101

// Visual Effects Section
#define IDC_CHECK_BLOOM 1200
#define IDC_LABEL_BLOOM_THRESH 1201
#define IDC_SLIDER_BLOOM_THRESH 1202
#define IDC_STATIC_BLOOM_THRESH 1203
#define IDC_LABEL_BLOOM_STR 1204
#define IDC_SLIDER_BLOOM_STR 1205
#define IDC_STATIC_BLOOM_STR 1206
#define IDC_LABEL_EXPOSURE 1207
#define IDC_SLIDER_EXPOSURE 1208
#define IDC_STATIC_EXPOSURE 1209
#define IDC_CHECK_FXAA 1210

// Fog Section
#define IDC_CHECK_FOG 1300
#define IDC_LABEL_FOG_DENSITY 1301
#define IDC_SLIDER_FOG_DENSITY 1302
#define IDC_STATIC_FOG_DENSITY 1303

// Particles Section
#define IDC_CHECK_PARTICLES 1400
#define IDC_LABEL_PARTICLE_CNT 1401
#define IDC_SLIDER_PARTICLE_CNT 1402
#define IDC_STATIC_PARTICLE_CNT 1403

// Scene Section
#define IDC_LABEL_ROTATION 1500
#define IDC_SLIDER_ROTATION 1501
#define IDC_STATIC_ROTATION 1502

// Camera Section
#define IDC_LABEL_CAM_DIST 1600
#define IDC_SLIDER_CAM_DIST 1601
#define IDC_STATIC_CAM_DIST 1602
#define IDC_LABEL_CAM_HEIGHT 1603
#define IDC_SLIDER_CAM_HEIGHT 1604
#define IDC_STATIC_CAM_HEIGHT 1605
#define IDC_LABEL_FOV 1606
#define IDC_SLIDER_FOV 1607
#define IDC_STATIC_FOV 1608

// Background Section
#define IDC_CHECK_SKYBOX 1700
#define IDC_LABEL_BG_R 1701
#define IDC_SLIDER_BG_R 1702
#define IDC_STATIC_BG_R 1703
#define IDC_LABEL_BG_G 1704
#define IDC_SLIDER_BG_G 1705
#define IDC_STATIC_BG_G 1706
#define IDC_LABEL_BG_B 1707
#define IDC_SLIDER_BG_B 1708
#define IDC_STATIC_BG_B 1709

// Buttons
#define IDC_BTN_DEFAULTS 1800

// =====================================================================
// METRIC CONTROLS
// =====================================================================

// CPU Metric
#define IDC_CHECK_CPU_ENABLED 2000
#define IDC_LABEL_CPU_THRESHOLD 2001
#define IDC_SLIDER_CPU_THRESHOLD 2002
#define IDC_STATIC_CPU_THRESHOLD 2003
#define IDC_LABEL_CPU_STRENGTH 2004
#define IDC_SLIDER_CPU_STRENGTH 2005
#define IDC_STATIC_CPU_STRENGTH 2006
#define IDC_LABEL_CPU_MESH 2007
#define IDC_COMBO_CPU_MESH 2008

// RAM Metric
#define IDC_CHECK_RAM_ENABLED 2100
#define IDC_LABEL_RAM_THRESHOLD 2101
#define IDC_SLIDER_RAM_THRESHOLD 2102
#define IDC_STATIC_RAM_THRESHOLD 2103
#define IDC_LABEL_RAM_STRENGTH 2104
#define IDC_SLIDER_RAM_STRENGTH 2105
#define IDC_STATIC_RAM_STRENGTH 2106
#define IDC_LABEL_RAM_MESH 2107
#define IDC_COMBO_RAM_MESH 2108

// Disk Metric
#define IDC_CHECK_DISK_ENABLED 2200
#define IDC_LABEL_DISK_THRESHOLD 2201
#define IDC_SLIDER_DISK_THRESHOLD 2202
#define IDC_STATIC_DISK_THRESHOLD 2203
#define IDC_LABEL_DISK_STRENGTH 2204
#define IDC_SLIDER_DISK_STRENGTH 2205
#define IDC_STATIC_DISK_STRENGTH 2206
#define IDC_LABEL_DISK_MESH 2207
#define IDC_COMBO_DISK_MESH 2208

// Network Metric
#define IDC_CHECK_NET_ENABLED 2300
#define IDC_LABEL_NET_THRESHOLD 2301
#define IDC_SLIDER_NET_THRESHOLD 2302
#define IDC_STATIC_NET_THRESHOLD 2303
#define IDC_LABEL_NET_STRENGTH 2304
#define IDC_SLIDER_NET_STRENGTH 2305
#define IDC_STATIC_NET_STRENGTH 2306
#define IDC_LABEL_NET_MESH 2307
#define IDC_COMBO_NET_MESH 2308

// =====================================================================
// LAYER LAYOUT CONTROLS
// =====================================================================

// Layer Selection
#define IDC_COMBO_LAYER_SELECT 3000
#define IDC_COMBO_LAYOUT_PRESET 3001

// Layer Position
#define IDC_LABEL_LAYER_X 3010
#define IDC_SLIDER_LAYER_X 3011
#define IDC_STATIC_LAYER_X 3012
#define IDC_LABEL_LAYER_Y 3013
#define IDC_SLIDER_LAYER_Y 3014
#define IDC_STATIC_LAYER_Y 3015

// Layer Size
#define IDC_LABEL_LAYER_W 3020
#define IDC_SLIDER_LAYER_W 3021
#define IDC_STATIC_LAYER_W 3022
#define IDC_LABEL_LAYER_H 3023
#define IDC_SLIDER_LAYER_H 3024
#define IDC_STATIC_LAYER_H 3025

// Layer Depth/Rotation
#define IDC_LABEL_LAYER_DEPTH 3030
#define IDC_SLIDER_LAYER_DEPTH 3031
#define IDC_STATIC_LAYER_DEPTH 3032
#define IDC_LABEL_LAYER_ROTATION 3033
#define IDC_SLIDER_LAYER_ROTATION 3034
#define IDC_STATIC_LAYER_ROTATION 3035

// Layer Options
#define IDC_CHECK_LAYER_VISIBLE 3040
#define IDC_CHECK_LAYER_LOCK_ASPECT 3041

// =====================================================================
// LAYER FX CONTROLS
// =====================================================================

// FX Layer Selection
#define IDC_COMBO_FX_LAYER_SELECT 4000
#define IDC_COMBO_BLEND_MODE 4001

// Bloom FX
#define IDC_CHECK_FX_BLOOM 4010
#define IDC_SLIDER_FX_BLOOM_THRESH 4011
#define IDC_STATIC_FX_BLOOM_THRESH 4012
#define IDC_SLIDER_FX_BLOOM_INT 4013
#define IDC_STATIC_FX_BLOOM_INT 4014
#define IDC_SLIDER_FX_BLOOM_RAD 4015
#define IDC_STATIC_FX_BLOOM_RAD 4016

// Glow FX
#define IDC_CHECK_FX_GLOW 4020
#define IDC_SLIDER_FX_GLOW_INT 4021
#define IDC_STATIC_FX_GLOW_INT 4022
#define IDC_SLIDER_FX_GLOW_SIZE 4023
#define IDC_STATIC_FX_GLOW_SIZE 4024
#define IDC_BTN_FX_GLOW_COLOR 4025

// Chromatic Aberration FX
#define IDC_CHECK_FX_CHROM 4030
#define IDC_SLIDER_FX_CHROM_OFFSET 4031
#define IDC_STATIC_FX_CHROM_OFFSET 4032

// Distortion FX
#define IDC_CHECK_FX_DISTORT 4040
#define IDC_SLIDER_FX_DISTORT_AMT 4041
#define IDC_STATIC_FX_DISTORT_AMT 4042
#define IDC_SLIDER_FX_DISTORT_FREQ 4043
#define IDC_STATIC_FX_DISTORT_FREQ 4044

// Trails FX
#define IDC_CHECK_FX_TRAILS 4050
#define IDC_SLIDER_FX_TRAIL_FADE 4051
#define IDC_STATIC_FX_TRAIL_FADE 4052

// Other FX Toggles
#define IDC_CHECK_FX_SCANLINES 4060
#define IDC_CHECK_FX_NOISE 4061
#define IDC_CHECK_FX_PIXELATE 4062
#define IDC_CHECK_FX_MOTIONBLUR 4063
#define IDC_CHECK_FX_VIGNETTE 4064
#define IDC_CHECK_FX_EDGEGLOW 4065

// Layer Opacity
#define IDC_SLIDER_FX_OPACITY 4070
#define IDC_STATIC_FX_OPACITY 4071

// Render Order
#define IDC_SLIDER_FX_RENDER_ORDER 4080
#define IDC_STATIC_FX_RENDER_ORDER 4081
